name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: Install clippy
              run: rustup component add clippy
            - name: Clone test repo
              run: |
                git clone https://github.com/heshanpadmasiri/gitwalker_test_repo.git ${{ env.TEST_REPO }}
              env:
                TEST_REPO: ${{ github.workspace }}/test_repo
            - name: Build and test
              run: |
                cargo build --verbose
                cargo test --verbose
              env:
                TEST_REPO: ${{ github.workspace }}/test_repo
            - name: Run Clippy
              run: cargo clippy -- -D warnings
            - name: Format code
              run: cargo fmt -- --check
